<?php

namespace Backend\AdminBundle\Repository;

/**
 * GalleryItemOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryItemOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
